// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/shaik-noor/full-stack-go-template/web/templ/components"
	"github.com/shaik-noor/full-stack-go-template/web/templ/layouts"
)

type SigninPageProps struct {
	Email            string
	Error            string
	Message          string
	MessageType      string // "info", "success", "warning", "error"
	Theme            string
	ThemeEnabled     bool
	EmailAuthEnabled bool
	OAuthEnabled     map[string]bool
}

func SigninForm(props SigninPageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Header --><div class=\"text-center mb-6\"><h1 class=\"text-2xl font-bold text-base-content\">Welcome back</h1><p class=\"text-base-content/60 mt-1\">Sign in to continue to your dashboard</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Error != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"alert alert-error mb-6 animate-scale-in\"><i data-lucide=\"alert-circle\" class=\"w-5 h-5 shrink-0\"></i> <span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Error)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/pages/auth/signin.templ`, Line: 28, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.Message != "" {
			var templ_7745c5c3_Var3 = []any{"alert mb-6 animate-scale-in",
				templ.KV("alert-info", props.MessageType == "info"),
				templ.KV("alert-success", props.MessageType == "success"),
				templ.KV("alert-warning", props.MessageType == "warning"),
				templ.KV("alert-error", props.MessageType == "error")}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var3).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/pages/auth/signin.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><i data-lucide=\"info\" class=\"w-5 h-5 shrink-0\"></i> <span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.Message)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/pages/auth/signin.templ`, Line: 38, Col: 24}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !props.EmailAuthEnabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"alert alert-warning mb-6 animate-scale-in\"><i data-lucide=\"alert-triangle\" class=\"w-5 h-5 shrink-0\"></i> <span>Email sign in is currently disabled. Please use Magic Link or Google Sign In.</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<form hx-post=\"/signin\" hx-target=\"#signin-content\" hx-swap=\"innerHTML\" class=\"space-y-5\"><!-- Email Field --><div class=\"form-control w-full\"><label class=\"label pb-1\" for=\"email\"><span class=\"label-text font-medium text-base-content\">Email address</span></label> <label class=\"input input-bordered w-full flex items-center gap-3 focus-within:input-primary transition-all duration-200\"><i data-lucide=\"mail\" class=\"w-5 h-5 text-base-content/40 shrink-0\"></i> <input type=\"email\" id=\"email\" name=\"email\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(props.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/pages/auth/signin.templ`, Line: 62, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" class=\"grow bg-transparent border-none focus:outline-none min-w-0\" placeholder=\"you@example.com\" required autocomplete=\"email\"></label></div><!-- Password Field --><div class=\"form-control w-full\" x-data=\"{ showPassword: false }\"><label class=\"label pb-1\" for=\"password\"><span class=\"label-text font-medium text-base-content\">Password</span> <a href=\"/forgot-password\" hx-boost=\"false\" class=\"label-text-alt link link-primary\">Forgot password?</a></label> <label class=\"input input-bordered w-full flex items-center gap-3 focus-within:input-primary transition-all duration-200\"><i data-lucide=\"lock\" class=\"w-5 h-5 text-base-content/40 shrink-0\"></i> <input :type=\"showPassword ? 'text' : 'password'\" id=\"password\" name=\"password\" class=\"grow bg-transparent border-none focus:outline-none min-w-0\" placeholder=\"Enter your password\" required autocomplete=\"current-password\"> <button type=\"button\" @click=\"showPassword = !showPassword\" class=\"btn btn-ghost btn-xs btn-circle shrink-0\"><i x-show=\"!showPassword\" data-lucide=\"eye\" class=\"w-4 h-4\"></i> <i x-show=\"showPassword\" data-lucide=\"eye-off\" class=\"w-4 h-4\" x-cloak></i></button></label></div><!-- Remember Me --><div class=\"form-control\"><label class=\"label cursor-pointer justify-start gap-3 py-0\"><input type=\"checkbox\" id=\"remember\" name=\"remember\" class=\"checkbox checkbox-primary checkbox-sm\"> <span class=\"label-text text-base-content/80\">Remember me for 7 days</span></label></div><!-- Submit Button --><button type=\"submit\" class=\"btn btn-primary w-full gap-2 text-base h-12 shadow-lg shadow-primary/25 hover:shadow-primary/40 transition-all duration-300\"><span class=\"htmx-indicator loading loading-spinner loading-sm\"></span> <i data-lucide=\"log-in\" class=\"w-5 h-5\"></i> Sign in</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<!-- Divider --><div class=\"divider text-base-content/40 text-sm my-6\">or continue with</div><!-- Social Login --><div class=\"space-y-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.OAuthEnabled["github"] {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<a href=\"/auth/github\" hx-boost=\"false\" class=\"btn bg-black text-white border-black w-full gap-2 h-11 hover:bg-black/90 transition-all duration-200\"><svg aria-label=\"GitHub logo\" width=\"16\" height=\"16\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"><path fill=\"white\" d=\"M12,2A10,10 0 0,0 2,12C2,16.42 4.87,20.17 8.84,21.5C9.34,21.58 9.5,21.27 9.5,21C9.5,20.77 9.5,20.14 9.5,19.31C6.73,19.91 6.14,17.97 6.14,17.97C5.68,16.81 5.03,16.5 5.03,16.5C4.12,15.88 5.1,15.9 5.1,15.9C6.1,15.97 6.63,16.93 6.63,16.93C7.5,18.45 8.97,18 9.54,17.76C9.63,17.11 9.89,16.67 10.17,16.42C7.95,16.17 5.62,15.31 5.62,11.5C5.62,10.39 6,9.5 6.65,8.79C6.55,8.54 6.2,7.5 6.75,6.15C6.75,6.15 7.59,5.88 9.5,7.17C10.29,6.95 11.15,6.84 12,6.84C12.85,6.84 13.71,6.95 14.5,7.17C16.41,5.88 17.25,6.15 17.25,6.15C17.8,7.5 17.45,8.54 17.35,8.79C18,9.5 18.38,10.39 18.38,11.5C18.38,15.32 16.04,16.16 13.81,16.41C14.17,16.72 14.5,17.33 14.5,18.26C14.5,19.6 14.5,20.68 14.5,21C14.5,21.27 14.66,21.59 15.17,21.5C19.14,20.16 22,16.42 22,12A10,10 0 0,0 12,2Z\"></path></svg> Sign in with GitHub</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.OAuthEnabled["google"] {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<a href=\"/auth/google\" hx-boost=\"false\" class=\"btn bg-white text-black border-[#e5e5e5] w-full gap-2 h-11 hover:shadow-primary/40 transition-all duration-200\"><svg aria-label=\"Google logo\" width=\"16\" height=\"16\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><g><path d=\"m0 0H512V512H0\" fill=\"#fff\"></path><path fill=\"#34a853\" d=\"M153 292c30 82 118 95 171 60h62v48A192 192 0 0190 341\"></path><path fill=\"#4285f4\" d=\"m386 400a140 175 0 0053-179H260v74h102q-7 37-38 57\"></path><path fill=\"#fbbc02\" d=\"m90 341a208 200 0 010-171l63 49q-12 37 0 73\"></path><path fill=\"#ea4335\" d=\"m153 219c22-69 116-109 179-50l55-54c-78-75-230-72-297 55\"></path></g></svg> Sign in with Google</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.OAuthEnabled["linkedin"] {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<a href=\"/auth/linkedin\" hx-boost=\"false\" class=\"btn bg-[#0967C2] text-white border-[#0059b3] w-full gap-2 h-11 hover:bg-[#0059b3] transition-all duration-200\"><svg aria-label=\"LinkedIn logo\" width=\"16\" height=\"16\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><path fill=\"white\" d=\"M26.111,3H5.889c-1.595,0-2.889,1.293-2.889,2.889V26.111c0,1.595,1.293,2.889,2.889,2.889H26.111c1.595,0,2.889-1.293,2.889-2.889V5.889c0-1.595-1.293-2.889-2.889-2.889ZM10.861,25.389h-3.877V12.87h3.877v12.519Zm-1.957-14.158c-1.267,0-2.293-1.034-2.293-2.31s1.026-2.31,2.293-2.31,2.292,1.034,2.292,2.31-1.026,2.31-2.292,2.31Zm16.485,14.158h-3.858v-6.571c0-1.802-.685-2.809-2.111-2.809-1.551,0-2.362,1.048-2.362,2.809v6.571h-3.718V12.87h3.718v1.686s1.118-2.069,3.775-2.069,4.556,1.621,4.556,4.975v7.926Z\" fill-rule=\"evenodd\"></path></svg> Sign in with LinkedIn</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div><!-- Sign Up Link --><p class=\"text-center text-base-content/60 mt-6\">Don't have an account? <a href=\"/signup\" class=\"link link-primary font-semibold hover:link-secondary transition-colors\">Sign up for free</a></p><script>\r\n    lucide.createIcons();\r\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SigninPage(props SigninPageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var8 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<style>\r\n    @keyframes float {\r\n        0%, 100% { transform: translate(0, 0) scale(1); }\r\n        33% { transform: translate(30px, -30px) scale(1.05); }\r\n        66% { transform: translate(-20px, 20px) scale(0.95); }\r\n    }\r\n    @keyframes float-reverse {\r\n        0%, 100% { transform: translate(0, 0) scale(1); }\r\n        33% { transform: translate(-40px, 20px) scale(1.1); }\r\n        66% { transform: translate(30px, -20px) scale(0.9); }\r\n    }\r\n    @keyframes pulse-glow {\r\n        0%, 100% { opacity: 0.4; }\r\n        50% { opacity: 0.7; }\r\n    }\r\n    .bg-blob-1 { animation: float 12s ease-in-out infinite, pulse-glow 4s ease-in-out infinite; }\r\n    .bg-blob-2 { animation: float-reverse 15s ease-in-out infinite, pulse-glow 5s ease-in-out infinite 1s; }\r\n    .bg-blob-3 { animation: float 10s ease-in-out infinite 2s, pulse-glow 6s ease-in-out infinite 2s; }\r\n    </style> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Navbar(nil, false, props.ThemeEnabled).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " <div class=\"min-h-screen flex items-center justify-center p-4 pt-20 relative overflow-hidden\"><div class=\"relative w-full max-w-md z-10\"><!-- Main Card --><div class=\"card bg-base-100/80 backdrop-blur-xl shadow-2xl border border-base-content/5\"><div class=\"card-body p-6 sm:p-8\" id=\"signin-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = SigninForm(props).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Auth("Sign In", "Sign in to your account", props.Theme, props.ThemeEnabled).Render(templ.WithChildren(ctx, templ_7745c5c3_Var8), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
