// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/noruj-official/full-stack-go-template/web/templ/components"
	"github.com/noruj-official/full-stack-go-template/web/templ/layouts"
)

type VerifyEmailPageProps struct {
	Success      bool
	Message      string
	Theme        string
	ThemeEnabled bool
}

func VerifyEmailPage(props VerifyEmailPageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\r\n    @keyframes float {\r\n        0%, 100% { transform: translate(0, 0) scale(1); }\r\n        33% { transform: translate(30px, -30px) scale(1.05); }\r\n        66% { transform: translate(-20px, 20px) scale(0.95); }\r\n    }\r\n    @keyframes float-reverse {\r\n        0%, 100% { transform: translate(0, 0) scale(1); }\r\n        33% { transform: translate(-40px, 20px) scale(1.1); }\r\n        66% { transform: translate(30px, -20px) scale(0.9); }\r\n    }\r\n    @keyframes pulse-glow {\r\n        0%, 100% { opacity: 0.4; }\r\n        50% { opacity: 0.7; }\r\n    }\r\n    .bg-blob-1 { animation: float 12s ease-in-out infinite, pulse-glow 4s ease-in-out infinite; }\r\n    .bg-blob-2 { animation: float-reverse 15s ease-in-out infinite, pulse-glow 5s ease-in-out infinite 1s; }\r\n    .bg-blob-3 { animation: float 10s ease-in-out infinite 2s, pulse-glow 6s ease-in-out infinite 2s; }\r\n    </style> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Navbar(nil, false, props.ThemeEnabled).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " <div class=\"min-h-screen flex items-center justify-center p-4 pt-20 relative overflow-hidden\"><div class=\"relative w-full max-w-md z-10\"><!-- Main Card --><div class=\"card bg-base-100/80 backdrop-blur-xl shadow-2xl border border-base-content/5\"><div class=\"card-body p-6 sm:p-8 text-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Success {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Success State --> <div class=\"mb-6\"><div class=\"inline-flex items-center justify-center w-20 h-20 bg-success/10 rounded-full mb-4 animate-scale-in\"><i data-lucide=\"check-circle\" class=\"w-12 h-12 text-success\"></i></div><h1 class=\"text-2xl font-bold text-base-content mb-2\">Email Verified!</h1><p class=\"text-base-content/60\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Message)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/pages/auth/verify_email.templ`, Line: 54, Col: 24}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div><!-- Sign In Button --> <a href=\"/signin\" class=\"btn btn-primary w-full gap-2 text-base h-12 shadow-lg shadow-primary/25 hover:shadow-primary/40 transition-all duration-300\"><i data-lucide=\"log-in\" class=\"w-5 h-5\"></i> Continue to Sign In</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<!-- Error State --> <div class=\"mb-6\"><div class=\"inline-flex items-center justify-center w-20 h-20 bg-error/10 rounded-full mb-4 animate-scale-in\"><i data-lucide=\"alert-circle\" class=\"w-12 h-12 text-error\"></i></div><h1 class=\"text-2xl font-bold text-base-content mb-2\">Verification Failed</h1><p class=\"text-base-content/60\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.Message)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/pages/auth/verify_email.templ`, Line: 73, Col: 24}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</p></div><!-- Action Buttons --> <div class=\"flex flex-col gap-3\"><a href=\"/signin\" class=\"btn btn-primary w-full gap-2\"><i data-lucide=\"log-in\" class=\"w-5 h-5\"></i> Go to Sign In</a> <a href=\"/signup\" class=\"btn btn-outline w-full gap-2\"><i data-lucide=\"user-plus\" class=\"w-5 h-5\"></i> Create New Account</a></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<!-- Additional Help --><div class=\"divider text-base-content/40 text-sm my-6\"></div><p class=\"text-sm text-base-content/60\">Need help? <a href=\"mailto:support@example.com\" class=\"link link-primary\">Contact Support</a></p></div></div></div></div><script>\r\n    lucide.createIcons();\r\n    </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Auth("Email Verification", "Verify your email address", props.Theme, props.ThemeEnabled).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
