// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/noruj-official/full-stack-go-template/internal/domain"
	"github.com/noruj-official/full-stack-go-template/web/templ/layouts"
)

func NotFound(title string, description string, user *domain.User, theme string, themeEnabled bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen flex flex-col items-center justify-center text-center pt-16\"><!-- Hero Content --><div class=\"max-w-2xl mx-auto px-4\"><div class=\"mb-6\"><span class=\"inline-flex items-center gap-2 px-3 py-1 rounded-full bg-base-200 text-base-content/70 text-sm\"><i data-lucide=\"alert-circle\" class=\"w-4 h-4\"></i> 404 Not Found</span></div><h1 class=\"text-3xl sm:text-4xl lg:text-5xl font-bold text-base-content mb-4\">This page doesn’t exist</h1><p class=\"text-base sm:text-lg text-base-content/70 mb-8\">The page you’re looking for was moved, deleted, or never existed.</p><div class=\"flex flex-wrap justify-center gap-3\"><a href=\"/\" class=\"btn btn-primary gap-2\"><i data-lucide=\"home\" class=\"w-5 h-5\"></i> Go back home</a> <a href=\"/signup\" class=\"btn btn-outline gap-2\"><i data-lucide=\"user-plus\" class=\"w-5 h-5\"></i> Create an account</a></div></div><!-- Illustration / Helpful Links --><div class=\"mt-12 max-w-3xl mx-auto px-4\"><div class=\"grid grid-cols-1 sm:grid-cols-2 gap-6\"><div class=\"card bg-base-100 border border-base-content/10\"><div class=\"card-body\"><h3 class=\"card-title text-base-content\">Popular pages</h3><ul class=\"space-y-2 text-sm\"><li><a href=\"/dashboard\" class=\"link link-hover\">Dashboard</a></li><li><a href=\"/signin\" class=\"link link-hover\">Sign in</a></li><li><a href=\"/signup\" class=\"link link-hover\">Sign up</a></li></ul></div></div><div class=\"card bg-base-100 border border-base-content/10\"><div class=\"card-body\"><h3 class=\"card-title text-base-content\">Need help?</h3><p class=\"text-base-content/70\">Try going back to the homepage or checking your URL.</p></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(title, description, user, false, theme, themeEnabled).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
