// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/noruj-official/full-stack-go-template/internal/domain"

func Navbar(user *domain.User, showSidebar bool, themeEnabled bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"fixed top-0 left-0 right-0 z-50 bg-base-100/90 backdrop-blur-xl border-b border-base-200 shadow-sm\"><div class=\"w-full px-4 sm:px-6 lg:px-8\"><div class=\"flex items-center justify-between h-16\"><!-- Left: sidebar toggle + brand title --><div class=\"flex items-center gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if showSidebar {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Mobile menu button --> <button @click=\"sidebarOpen = !sidebarOpen\" class=\"lg:hidden btn btn-ghost p-2\" title=\"Open Menu\"><i data-lucide=\"menu\" class=\"w-5 h-5\"></i></button><!-- Desktop sidebar toggle button --> <button @click=\"sidebarOpen = !sidebarOpen\" class=\"hidden lg:inline-flex btn btn-ghost p-2\" title=\"Toggle Sidebar\"><i data-lucide=\"panel-left\" class=\"w-5 h-5\"></i></button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Disabled toggles on auth pages with tooltip --> <div class=\"tooltip tooltip-right lg:tooltip-bottom z-50\" data-tip=\"Sidebar is disabled on auth pages\"><button class=\"lg:hidden btn btn-ghost p-2 opacity-50 cursor-not-allowed\" title=\"Sidebar disabled\" disabled><i data-lucide=\"menu\" class=\"w-5 h-5\"></i></button></div><div class=\"tooltip tooltip-right lg:tooltip-bottom z-50\" data-tip=\"Sidebar is disabled on auth pages\"><button class=\"hidden lg:inline-flex btn btn-ghost p-2 opacity-50 cursor-not-allowed\" title=\"Sidebar disabled\" disabled><i data-lucide=\"panel-left\" class=\"w-5 h-5\"></i></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- Brand Logo/Title moved next to toggle --><a href=\"/\" class=\"flex items-center gap-2 px-2\"><span class=\"text-xl font-bold text-base-content\">Full Stack Go Template</span></a></div><!-- Right side actions --><div class=\"flex items-center gap-2\"><!-- Dark mode toggle -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if themeEnabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<button @click=\"darkMode = !darkMode\" class=\"btn btn-ghost p-2\" :title=\"darkMode ? 'Switch to light mode' : 'Switch to dark mode'\"><i x-show=\"!darkMode\" data-lucide=\"moon\" class=\"w-5 h-5\"></i> <i x-show=\"darkMode\" data-lucide=\"sun\" class=\"w-5 h-5\" x-cloak></i></button> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if user != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- User menu (authenticated) --> <div class=\"dropdown dropdown-end\" x-data=\"{ open: false }\" :class=\"{ 'dropdown-open': open }\"><button @click=\"open = !open\" @click.away=\"open = false\" class=\"flex items-center gap-2 p-1.5 rounded-xl hover:bg-base-200 transition-colors\"><div class=\"avatar\"><div class=\"w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center text-primary text-sm font-medium overflow-hidden\"><img class=\"w-full h-full object-cover\" src=\"/u/profile/image\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 56, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" onerror=\"this.style.display='none'; this.nextElementSibling.style.display='flex';\" onload=\"this.style.display='block'; this.nextElementSibling.style.display='none';\"> <span class=\"w-full h-full flex items-center justify-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(user.Name) > 0 {
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(string([]rune(user.Name)[0]))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 62, Col: 42}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span></div></div><span class=\"hidden sm:block text-sm font-medium text-base-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 67, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span> <i data-lucide=\"chevron-down\" class=\"w-4 h-4 text-base-content/50 hidden sm:block\"></i></button><ul x-show=\"open\" x-transition:enter=\"transition ease-out duration-200\" x-transition:enter-start=\"opacity-0 scale-95\" x-transition:enter-end=\"opacity-100 scale-100\" x-transition:leave=\"transition ease-in duration-150\" x-transition:leave-start=\"opacity-100 scale-100\" x-transition:leave-end=\"opacity-0 scale-95\" class=\"menu dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-56 border border-base-200\"><li class=\"menu-title px-4 py-2 border-b border-base-200 mb-2\"><span class=\"text-base-content block text-sm font-medium\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 81, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span> <span class=\"text-base-content/70 block text-xs font-normal\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(user.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 82, Col: 82}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 = []any{"inline-flex items-center mt-1 px-2 py-0.5 rounded text-xs font-medium",
				templ.KV("badge badge-primary", user.Role.String() == "super_admin"),
				templ.KV("badge badge-secondary", user.Role.String() == "admin"),
				templ.KV("badge badge-ghost", user.Role.String() != "super_admin" && user.Role.String() != "admin")}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var7...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<span class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var7).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(user.Role.String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templ/components/navbar.templ`, Line: 87, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</span></li><li><a href=\"/u/profile\"><i data-lucide=\"user\" class=\"w-4 h-4\"></i> Profile</a></li><li><a href=\"/u/settings\"><i data-lucide=\"settings\" class=\"w-4 h-4\"></i> Settings</a></li><div class=\"divider my-1\"></div><li><form action=\"/logout\" method=\"POST\" class=\"w-full\"><button type=\"submit\" class=\"w-full flex items-center gap-3 text-error hover:bg-error/10\"><i data-lucide=\"log-out\" class=\"w-4 h-4\"></i> Logout</button></form></li></ul></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<!-- Auth buttons (not authenticated) --> <a href=\"/signin\" class=\"btn btn-ghost text-sm\">Sign in</a> <a href=\"/signup\" class=\"btn btn-primary text-sm\">Sign up</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
